# Generated by Django 4.2.2 on 2023-06-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_requestlostitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlostitem',
            name='place',
            field=models.CharField(choices=[('F', 'Frist Floor'), ('S', 'Secound Floor'), ('T', 'Third Floor')], default='T', max_length=100),
        ),
        migrations.AlterField(
            model_name='requestlostitem',
            name='status',
            field=models.CharField(choices=[('T', 'TRAKING'), ('M', 'MATCHED'), ('F', 'FOUND')], default='F', max_length=100),
        ),
    ]
