# Generated by Django 4.2.2 on 2023-06-15 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_requestlostitem_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlostitem',
            name='Sub_catagory',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.subcatagory'),
        ),
        migrations.AlterField(
            model_name='requestlostitem',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('R', 'Red'), ('G', 'Green'), ('B', 'Blue'), ('BLA', 'Black'), ('Y', 'Yellow'), ('W', 'White')], default='B', max_length=100)),
                ('place', models.CharField(choices=[('F', 'Frist Floor'), ('S', 'Secound Floor'), ('T', 'Third Floor')], default='T', max_length=100)),
                ('discription', models.TextField()),
                ('image', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('T', 'TRAKING'), ('M', 'MATCHED'), ('F', 'FOUND')], default='F', max_length=100)),
                ('Sub_catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.subcatagory')),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.catagory')),
            ],
        ),
    ]
