# Generated by Django 4.2.2 on 2023-06-15 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_requestlostitem_sub_catagory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlostitem',
            name='Sub_catagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.subcatagory'),
        ),
    ]
