# Generated by Django 4.2.2 on 2023-06-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_discription_requestlostitem_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='founditem',
            old_name='discription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='founditem',
            name='status',
            field=models.CharField(choices=[('T', 'TRAKING'), ('M', 'MATCHED'), ('F', 'FOUND'), ('N', 'NOMATCH')], default='T', max_length=100),
        ),
        migrations.AlterField(
            model_name='requestlostitem',
            name='status',
            field=models.CharField(choices=[('T', 'TRAKING'), ('M', 'MATCHED'), ('F', 'FOUND')], default='T', max_length=100),
        ),
    ]
