# Generated by Django 4.2.2 on 2023-06-16 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_discription_requestlostitem_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='founditem',
            old_name='discription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='catagory',
            name='name',
            field=models.CharField(default='Empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='status',
            field=models.CharField(choices=[('T', 'TRAKING'), ('M', 'MATCHED'), ('F', 'FOUND'), ('N', 'NOMATCH')], default='T', max_length=100),
        ),
        migrations.AlterField(
            model_name='requestlostitem',
            name='description',
            field=models.TextField(default='Null'),
        ),
        migrations.AlterField(
            model_name='requestlostitem',
            name='place',
            field=models.CharField(choices=[('F', 'Frist Floor'), ('S', 'Secound Floor'), ('T', 'Third Floor')], default='F', max_length=100),
        ),
        migrations.AlterField(
            model_name='requestlostitem',
            name='status',
            field=models.CharField(choices=[('T', 'TRAKING'), ('M', 'MATCHED'), ('F', 'FOUND')], default='T', max_length=100),
        ),
        migrations.AlterField(
            model_name='subcatagory',
            name='name',
            field=models.CharField(default='Empty', max_length=100),
        ),
        migrations.CreateModel(
            name='LostItemOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=13)),
                ('request_Lost_Item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.requestlostitem')),
            ],
        ),
    ]
