# Generated by Django 4.2.1 on 2023-06-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_discription_founditem_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='email',
            field=models.EmailField(default=' ', max_length=254),
        ),
        migrations.AddField(
            model_name='founditem',
            name='name',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='founditem',
            name='phone_number',
            field=models.CharField(default=' ', max_length=13),
        ),
    ]
