# Generated by Django 4.2.2 on 2023-06-17 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_discription_founditem_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostItemOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=13)),
                ('request_Lost_Item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.requestlostitem')),
            ],
        ),
    ]
