# Generated by Django 4.2.1 on 2023-06-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_founditem_email_founditem_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founditem',
            name='email',
        ),
        migrations.RemoveField(
            model_name='founditem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='founditem',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='requestlostitem',
            name='email',
            field=models.EmailField(default=' ', max_length=254),
        ),
        migrations.AddField(
            model_name='requestlostitem',
            name='name',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='requestlostitem',
            name='phone_number',
            field=models.CharField(default=' ', max_length=13),
        ),
    ]
