# Generated by Django 4.2.2 on 2023-06-17 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_lostitemowner'),
        ('main_app', '0009_remove_founditem_email_remove_founditem_name_and_more'),
    ]

    operations = [
    ]
