# Generated by Django 4.2.2 on 2023-06-17 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_merge_20230617_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confirm', models.BooleanField(default=False)),
                ('found_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.founditem')),
                ('request_Lost_Item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.requestlostitem')),
            ],
        ),
        migrations.DeleteModel(
            name='LostItemOwner',
        ),
    ]
