# Generated by Django 4.2.2 on 2023-06-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_confirmitem_delete_lostitemowner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlostitem',
            name='status',
            field=models.CharField(choices=[('T', 'TRAKING'), ('M', 'MATCHED'), ('F', 'FOUND'), ('N', 'NOMATCH')], default='T', max_length=100),
        ),
    ]
