# Generated by Django 4.2.2 on 2023-06-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmitem',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='confirmitem',
            name='message_form',
            field=models.TextField(default=' '),
        ),
    ]
