# Generated by Django 4.2.2 on 2023-06-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_confirmitem_is_reserved_confirmitem_message_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlostitem',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
