# Generated by Django 4.2.2 on 2023-06-20 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_requestlostitem_image'),
        ('main_app', '0015_confirmitem_is_send'),
    ]

    operations = [
    ]
