# Generated by Django 4.2.2 on 2023-06-21 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_merge_20230620_2012'),
        ('main_app', '0016_merge_20230620_2226'),
    ]

    operations = [
    ]
