# Generated by Django 4.2.2 on 2023-06-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_merge_20230621_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcatagory',
            name='name',
            field=models.CharField(default='Other', max_length=100),
        ),
    ]
