# Generated by Django 4.2.2 on 2023-06-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_alter_subcatagory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmitem',
            name='from_ai',
            field=models.BooleanField(default=False),
        ),
    ]
